"""pasted_duration_is_nullable

Revision ID: 8665852e940e
Revises: c477e80d4a0c
Create Date: 2026-06-27 18:07:49.442981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8665852e940e'
down_revision: Union[str, Sequence[str], None] = 'c477e80d4a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pasted', 'duration',
               existing_type=postgresql.ENUM('oneTime', 'oneDay', 'tenDays', name='duration'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    UPDATE pasted
    SET duration = 'oneTime'
    WHERE duration IS NULL
    """)
    op.alter_column('pasted', 'duration',
               existing_type=postgresql.ENUM('oneTime', 'oneDay', 'tenDays', name='duration'),
               nullable=False)
    # ### end Alembic commands ###
