"""motd_column_branding_table

Revision ID: 89783081c09c
Revises: 8665852e940e
Create Date: 2026-07-28 14:22:23.681072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89783081c09c'
down_revision: Union[str, Sequence[str], None] = '8665852e940e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branding', sa.Column('message_of_the_day', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branding', 'message_of_the_day')
    # ### end Alembic commands ###
