"""drop_password_reset_in_admin_schema

Revision ID: a9281c654e6e
Revises: 89783081c09c
Create Date: 2026-09-08 14:57:58.138473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9281c654e6e'
down_revision: Union[str, Sequence[str], None] = '89783081c09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_reset_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_reset_required', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###
