"""branding_table

Revision ID: c477e80d4a0c
Revises: ef9f337aeec5
Create Date: 2026-06-23 11:33:02.846825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c477e80d4a0c'
down_revision: Union[str, Sequence[str], None] = 'ef9f337aeec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding',
    sa.Column('app_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('support_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('privacy_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(
        sa.table(
            "branding",
            sa.column("app_name", sa.String),
            sa.column("app_description", sa.String),
            sa.column("support_email", sa.String),
            sa.column("privacy_policy", sa.String),
        ),
        [
            {"app_name": "PasteBin",
             "app_description": "A Public, generic pastebin service",
             "support_email": "hi@example.org",
             "privacy_policy": """
# Privacy Policy

Your privacy matters.

This website does not require user accounts and does not intentionally collect or store personal information.

The only content we store is the text you choose to submit so it can be shared using its unique link.

Like most websites, the server may automatically generate basic logs (such as IP addresses and request times) for security and operational purposes. These logs are not used to identify users and are retained only as long as necessary.

Please do not submit sensitive or confidential information, as anyone with the paste link may be able to access its contents.
             """},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('branding')
    # ### end Alembic commands ###
