"""cleanup_pasted_and_expiry_duration_index

Revision ID: ef9f337aeec5
Revises: 46eb91fef40a
Create Date: 2026-06-22 21:16:54.944536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9f337aeec5'
down_revision: Union[str, Sequence[str], None] = '46eb91fef40a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_index(op.f('ix_expiry_duration_is_enabled'), 'expiry_duration', ['is_enabled'], unique=False)

    ## Alembic is being dumb here? The nullability of the table has been applied in previous rivision.
    op.alter_column('pasted', 'duration',
               existing_type=postgresql.ENUM('oneTime', 'oneDay', 'tenDays', name='duration'),
               nullable=False)

    ## Redundent and good to drop. Indexing is already in place by the side effect of uniqueness of shortcode column.
    op.drop_index(op.f('ix_pasted_shortcode'), table_name='pasted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pasted_shortcode'), 'pasted', ['shortcode'], unique=True)
    op.alter_column('pasted', 'duration',
               existing_type=postgresql.ENUM('oneTime', 'oneDay', 'tenDays', name='duration'),
               nullable=True)
    op.drop_index(op.f('ix_expiry_duration_is_enabled'), table_name='expiry_duration')
    # ### end Alembic commands ###
