x-common-env: &common-env
  PASTORE_JWT_SECRET: supersecret
  PASTORE_INITIAL_ADMIN_PASSWORD: Supersecret1234 # Must include number and letter

  PASTORE_DATABASE_HOST: db
  PASTORE_DATABASE_NAME: &db_name pastore
  PASTORE_DATABASE_PASSWORD: &db_password changeme
  PASTORE_DATABASE_USERNAME: &db_user pastore

  # Optional
  PASTORE_LOG_STRUCTURED: False
  PASTORE_LOG_LEVEL: info

  # Optional
  PASTORE_Metrics_Enabled: False
  PASTORE_Metrics_Username: "pastore" 
  PASTORE_Metrics_Password: "secret"
  
  
  # Optional
  PASTORE_REDIS_ENABLED: False
  PASTORE_REDIS_HOST: 127.0.0.1
  PASTORE_REDIS_PORT: 6379
  PASTORE_REDIS_PASSWORD: secret


services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
        POSTGRES_PASSWORD: *db_password
        POSTGRES_USER: *db_user
        POSTGRES_DB: *db_name
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 3s
      retries: 3


  migrate:
    image: parsajr/pastore
    command: uv run alembic -c ./app/alembic.ini upgrade head
    environment:
        <<: *common-env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    image: parsajr/pastore
    environment:
        <<: *common-env

    depends_on: 
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  postgres-data:
